name: Node.js CI/CD

on:
  push:
    branches:
      - develop  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Push to main on success
        env:
          PAT_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b main
          git merge develop
          git push --set-upstream origin main
